name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for new Containerlab release
      id: check_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/srl-labs/containerlab/releases/latest | jq -r .tag_name)
        echo "Latest Containerlab release: $latest_release"
        echo "CONTAINERLAB_VERSION=${latest_release#v}" >> $GITHUB_ENV
        
        # Check if we need to build a new image
        if ! docker pull ghcr.io/${{ github.repository }}:$latest_release &> /dev/null; then
          echo "BUILD_NEEDED=true" >> $GITHUB_ENV
        else
          echo "BUILD_NEEDED=false" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      if: env.BUILD_NEEDED == 'true'
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: env.BUILD_NEEDED == 'true'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: env.BUILD_NEEDED == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ env.CONTAINERLAB_VERSION }}
        build-args: |
          CONTAINERLAB_VERSION=${{ env.CONTAINERLAB_VERSION }}

    - name: Update README
      if: env.BUILD_NEEDED == 'true'
      run: |
        sed -i 's/CONTAINERLAB_VERSION="[0-9.]*"/CONTAINERLAB_VERSION="${{ env.CONTAINERLAB_VERSION }}"/' README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "Update Containerlab version to ${{ env.CONTAINERLAB_VERSION }}"
        git push